development:
  aws_access_key_id: AKIAJ77EM7MALMT3WOPA
  aws_secret_access_key: 2+lym6URH7P0yKl9x1kFVcsUcWGVRU+MhOfyqjzc
  salt: your_aws_sdb_proxy_secret_salt_here
  port: 8888

test:
  aws_access_key_id: AKIAJ77EM7MALMT3WOPA
  aws_secret_access_key: 2+lym6URH7P0yKl9x1kFVcsUcWGVRU+MhOfyqjzc
  salt: your_aws_sdb_proxy_secret_salt_here
  port: 8888

production:
  aws_access_key_id: AKIAJ77EM7MALMT3WOPA
  aws_secret_access_key: 2+lym6URH7P0yKl9x1kFVcsUcWGVRU+MhOfyqjzc
  salt: your_aws_sdb_proxy_secret_salt_here
  port: 8888
